### ISSUE TITLE
The entry file "styles/main.css" does not exist even though styleEntries is set correct

### ISSUE THREAD

**Issue by t0byman** [brandcom/cakephp-vite#10]
See title. I have:
```
        'development' => [
            'scriptEntries' => ['scripts/main.ts'],
            'styleEntries' => ['styles/main.css'],
            'url' => 'http://localhost:5173',
        ],
```
It can find the main.ts but not the main.css, also I think you should be able to not set styleEntries at all and not have it give the error `There are no valid entry points for the dev server. Be sure to set the ViteHelper.development.scriptEntries config.` or if you decide to keep it change the error for styles to `Be sure to set the ViteHelper.development.styleEntries config`.

**Comment by passchn** [comment]
@t0byman I made the error messages a bit more clear now. Still, your config is correct, but you should now get the third exception: https://github.com/brandcom/cakephp-vite/blob/ad870751c0f072f4186f2140d63ce38fd0df7d81/src/View/Helper/ViteScriptsHelper.php#L212 

I don't really understand why you get the `There are no valid entry points ...` error right now. What is your trace? Does it come from `::css()` or `::script()`?

> "I think you should be able to not set styleEntries at all [...]"

If you want to user `::css()` during development, the helper will need an entryPoint. Otherwise, what should the helper do? You would get a blank page instead. 

As I am importing my css in js, I don't use `::css()` at all, so I don't need to set the config.

**Comment by t0byman** [comment]
@passchn Can you deploy alpha6 so I can test?

**Comment by passchn** [comment]
@t0byman https://github.com/brandcom/cakephp-vite/releases/tag/v1-alpha6

**Comment by passchn** [comment]
If it is not working, could you please debug `$config` inside `ViteScriptsHelper::getFilesForDevelopment()`?

**Comment by t0byman** [comment]
Let's talk on Twitter DM https://twitter.com/t0byman

**Comment by t0byman** [comment]
This is fixed now, closing
